[tool.black]
line-length = 99
exclude = '''
/(
    \.git
  | __pycache__
  | bin
  | client
  | cuberite
  | cuberite_config
  | cuberite_plugins
  | writeups
  | python/craftassist/ttad/generation
  | python/craftassist/ttad/generation_dialogues
)/
'''

[tool.pytest.ini_options]
addopts = "--ignore 'droidlet/lowlevel/minecraft/server' --ignore 'droidlet/lowlevel/minecraft/client'"

